namespace WS.XMLLayer.WebMethods
{
	public enum StatusInfoCode
	{
		Success = 0,
		NothingAvailableForGivenDates = 2,
		PropertyHasNoPriceSettingsForGivenDates = 3,
		UnexpectedError = 17,
		YouAreNotTheOwnerOfTheApartment = 24,
		PropertyDoesNotExist = 56,
		DateFromHasToBeEarlierThanDateTo = 74,
		NumberOfGuestsTooHigh = 76,
		NOPPositiveCalueRequired = 77,
		StayPeriodDoesntMatchWithMinimumStay = 79,
		ApartmentIsArchivedOrNLAOrNotActive = 82,
		StayPeriodDoesntMatchWithChangeover = 89,
		SomeOfRequiredFieldsWereNotFilled = 94,
		InvalidStandardNumberOfGuests_Negative = 97,
		MinStaysNotSatisfied = 115,
		MissingMandatoryElement = 0x7F,
		InvalidCurrency = 134,
		RequestRejectedByPartner = 135,
		CheckPMSSettings = 158,
		YouAreNoPermittedToListThisUsersReservations = 161,
		CanNotProcessARequestBecauseApartmentIsConnectedToRMS = 169,
		InvalidAdditionalDataXml = 171,
		PtbaNotSatisfied = 172,
		LongStayNrOfNightsTrimmed = 173,
		InvalidFrenchTaxCategory = 174,
		InvalidFrenchResidenceType = 175,
		RequestConfirmationInExternalSystemFailed = 176,
		PropertyNotConnectedToExternalSystem = 177,
		CannotCancelSCReservationInRU = 178,
		AdditionalFeeValueNotPositive = 179,
		SeasonInfoCanNotContainsLOSPricesAndFullStayPrices = 180,
		NumberOfUnitsInMultiunitPropertyCanNotBeDecreased = 181,
		SeasonInfoCanNotContainsEGPSAndFullStayPrices = 182,
		SeasonInfoCanNotContainsExtraAndFullStayPrices = 183,
		SeasonInfoWithFSPCanNotBeLongerThenOneDay = 184,
		SeasonInfoCanNotContainsFSPWithTheSameNrOfGuestsAndNights = 185,
		FspSeasonInfoCanNotBeMixedWithPriceInfoWithPriceOnly = 186,
		MissingOwnerID = 187,
		InvalidLanguageCaption = 188,
		InvalidLanguageDescription = 189,
		MissingImageReferenceID = 190,
		DuplicateCaptionLanguageID = 191,
		DuplicateDescriptionLanguageID = 192,
		InvalidImageTypeID = 193,
		FSPRowsCanNotBeDefinedForTheSameDayWithTheSameNumberOfGuests = 194,
		PricesWithSameNumberOfGuestsCanNotBeDefinedInOneFSPRow = 195,
		DefaultPriceHasToBePositiveValue = 196,
		PriceInPricePerNightHasToBePositiveValue = 197,
		FspRowPricePerNightNrOfNightsCanNotBeLongerThanRUMax = 198,
		FSPRowDefaultPriceCanNotBeSpecifiedWithoutAnyFSPRows = 199,
		DateToCanNotBeInThePast = 200,
		CantUseOwnerAndUsername = 201
	}
}
